"""add hashed_password and refresh token fields

Revision ID: 41d1c96a8040
Revises: 6a8459eb6497
Create Date: 2025-12-17 04:27:24.640219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d1c96a8040'
down_revision: Union[str, Sequence[str], None] = '6a8459eb6497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token', sa.String(length=64), nullable=False))
    op.add_column('refresh_tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('revoked', sa.Boolean(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'created_at')
    op.drop_column('refresh_tokens', 'revoked')
    op.drop_column('refresh_tokens', 'expires_at')
    op.drop_column('refresh_tokens', 'token')
    # ### end Alembic commands ###
